import React from 'react';
import { motion } from 'framer-motion';
import { Check, X } from 'lucide-react';

interface ComparisonRow {
  feature: string;
  devlix: string;
  devlixPass: boolean;
  others: string;
  othersPass: boolean;
}

const comparisonData: ComparisonRow[] = [
  {
    feature: 'Average Loading Speed',
    devlix: 'Sub-250ms (Lightning Fast)',
    devlixPass: true,
    others: '2.5s - 4.5s (Standard templates)',
    othersPass: false,
  },
  {
    feature: 'Animation Experience',
    devlix: '60 FPS Hardware-Accelerated (GSAP & Lenis)',
    devlixPass: true,
    others: 'Choppy, template-level scroll or none',
    othersPass: false,
  },
  {
    feature: 'SEO & Structured Data',
    devlix: 'Custom canonical paths, dynamic sitemaps & Schema tags',
    devlixPass: true,
    others: 'Autogenerated generic plugin descriptions',
    othersPass: false,
  },
  {
    feature: 'Accessibility Standards',
    devlix: 'WCAG AA Compliant, Screen-reader & Visible Focus states',
    devlixPass: true,
    others: 'Ignored focus parameters, low contrast',
    othersPass: false,
  },
  {
    feature: 'Performance Score',
    devlix: '100% Lighthouse Score Guaranteed',
    devlixPass: true,
    others: '40% - 65% due to bloated assets & trackers',
    othersPass: false,
  },
  {
    feature: 'Technical Support',
    devlix: '24/7 dedicated contact channels & direct slack integrations',
    devlixPass: true,
    others: 'Email support queues (2-3 business days)',
    othersPass: false,
  },
  {
    feature: 'Scalability / Database',
    devlix: 'Serverless Edge routing, offline syncing (Supabase)',
    devlixPass: true,
    others: 'Shared server databases, legacy monoliths',
    othersPass: false,
  },
  {
    feature: 'Code Maintainability',
    devlix: '100% custom React/TS code, typed schemas, clean components',
    devlixPass: true,
    others: 'Bloated WordPress builders or drag-and-drop engines',
    othersPass: false,
  },
  {
    feature: 'Product Security',
    devlix: 'Custom Auth keys, secure Edge environment variables',
    devlixPass: true,
    others: 'Prone to injection attacks, plugins updates failures',
    othersPass: false,
  },
];

export const WhyDevlix: React.FC = () => {
  return (
    <section id="why-us" className="py-24 md:py-32 bg-white relative optimize-render">
      <div className="max-w-7xl mx-auto px-6 md:px-8">
        {/* Section Header */}
        <div className="max-w-3xl mb-20 text-left">
          <span className="text-[13px] font-bold text-primaryGreen block mb-3 uppercase tracking-wider">
            Why Partner With Devlix
          </span>
          <h2 className="text-[36px] md:text-[54px] font-extrabold text-dark leading-tight">
            Setting the engineering standard.
          </h2>
          <p className="text-[16px] md:text-[18px] text-dark/70 mt-4 leading-relaxed">
            We don't settle for average frameworks or bloated software builders. We measure success by millisecond speeds and user retention.
          </p>
        </div>

        {/* Comparison Table Grid */}
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: '-100px' }}
          transition={{ duration: 0.6 }}
          className="overflow-x-auto rounded-2xl border border-black/5 shadow-premium bg-secondaryBg/30 p-1 md:p-4"
        >
          <table className="w-full text-left border-collapse min-w-[700px]">
            <thead>
              <tr className="border-b border-black/[0.06]">
                <th className="py-5 px-6 text-xs font-bold uppercase tracking-widest text-dark/65 font-mono">Performance Indicator</th>
                <th className="py-5 px-6 text-xs font-bold uppercase tracking-widest text-primaryGreen font-mono bg-primaryGreen/5 rounded-t-xl">Devlix Studio</th>
                <th className="py-5 px-6 text-xs font-bold uppercase tracking-widest text-dark/65 font-mono">Other Agencies</th>
              </tr>
            </thead>
            <tbody>
              {comparisonData.map((row) => (
                <tr
                  key={row.feature}
                  className={`border-b border-black/[0.04] last:border-0 hover:bg-black/[0.01] transition-colors duration-150`}
                >
                  {/* Feature name */}
                  <td className="py-5 px-6 font-semibold text-[14px] md:text-[15px] text-dark">
                    {row.feature}
                  </td>
                  
                  {/* Devlix Studio Cell */}
                  <td className="py-5 px-6 bg-primaryGreen/[0.02] border-x border-primaryGreen/[0.04]">
                    <div className="flex items-center gap-3">
                      <div className="w-5 h-5 rounded-full bg-primaryGreen/10 flex items-center justify-center shrink-0">
                        <Check className="w-3.5 h-3.5 text-accentGreen" />
                      </div>
                      <span className="font-bold text-[14px] text-dark">{row.devlix}</span>
                    </div>
                  </td>

                  {/* Other Agencies Cell */}
                  <td className="py-5 px-6">
                    <div className="flex items-center gap-3">
                      <div className="w-5 h-5 rounded-full bg-red-100 flex items-center justify-center shrink-0">
                        <X className="w-3.5 h-3.5 text-red-500" />
                      </div>
                      <span className="text-[14px] text-dark/70">{row.others}</span>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </motion.div>
      </div>
    </section>
  );
};
export default WhyDevlix;
